[package]
name = "ankisyncd"
version = "0.1.3"
edition = "2018"
license = "AGPL-3.0-or-later"
documentation = "https://docs.rs/ankisyncd/"
readme = "README.md"
description="a personal Anki(flash-card app) sync server"
keywords = ["Anki","actix-web","server"]
repository = "https://github.com/ankicommunity/anki-sync-server-rs.git"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "build.rs"

[dependencies]
thiserror = "1.0.30"
actix-web = { version = "3", features=["rustls"]}
actix-multipart = "0.3"
async-std = "1.8"
futures-util = "0.3"
bytes="0.5.6"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
flate2 = "1.0.22"
env_logger = "0.8"
config = "0.11.0"
rand = "0.8.4"
sha2 = "0.9.5"
md5 = "0.7.0"
urlparse = "0.7.3"
hex = "0.4.3"
anki={path="anki/rslib"}
clap="3.0.0-beta.5"
[dependencies.rusqlite]
version = "0.25.1"
features = ["bundled"]

[dependencies.rustls]
optional = true
version = "0.18"